name: lamvng-finance-tracker

version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file: .env

volumes:
  postgres-data:

networks:
  default:
