name: lamvng-finance-tracker

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: finance-tracker-db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: 0.0.0.0
      POSTGRES_PORT: 5432
      POSTGRES_DB: finance-tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6673a613-b827-46ed-90dc-3295c4bdef89


volumes:
  postgres-data:

networks:
  default:
